# Generated by Django 5.1 on 2024-09-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitens',
            old_name='course',
            new_name='category',
        ),
    ]
