# Generated by Django 5.1 on 2024-09-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPP', '0002_rename_course_menuitens_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitens',
            old_name='name',
            new_name='item_name',
        ),
    ]
