# Generated by Django 5.1 on 2024-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_remove_menuitem_inventory_menuitem_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
