# Generated by Django 4.1.3 on 2024-09-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drink',
            new_name='drink_name',
        ),
    ]
